CREATE DATABASE IF NOT EXISTS vehiclee;
GRANT ALL  PRIVILEGES ON vehiclee TO root;
FLUSH PRIVILEGES;

USE vehiclee;

CREATE TABLE IF NOT EXISTS user(
user_name VARCHAR(30) NOT NULL PRIMARY KEY,
email_id VARCHAR (100),
phone_num VARCHAR (10)
);

CREATE TABLE IF NOT EXISTS vehicle(
vehicle_type VARCHAR(30),
model VARCHAR(30) PRIMARY KEY,
capacity VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Credentials(
user_name VARCHAR(30) NOT NULL PRIMARY KEY,
password VARCHAR(20) NOT NULL
);